layouts/main.js
Cette PR remplace la description de page par défaut.
`Concentrer la connaissance et restituer la consistance des projets PCRS en cours et des territoires à prospecter` est remplacé par `Accompagner et diffuser les projets locaux de PCRS en cours et à venir`
=> Changement de la description de la page par défaut

pages/blog/lancement.js
Cette PR corrige les liens relatifs sur la page `/blog/lancement`
=> Corrige les liens de la page lancement

components/follow.js, components/section-image.js, components/section.js, pages/blog/lancement.js, pages/declaration-accessibilite.js, pages/index.js, pages/mentions-legales.js
Cette PR propose d’ajouter un composant `Section` facilement réutilisable.
Le précédent composant `Section` a été renommé `SectionImage` .
Les paramètres du nouveau composant sont les suivants : 
- `title` : Titre de la section
- `subtitle` : Sous-titre de la section
- `background` : couleur de l’arrière-plan de la section : 
- `primary`
- `secondary`
- `dark`
- `blue`
- `children` : composant enfant de la section
=> Ajout d’un composant Section

pages/blog/lancement.js
Un oubli a causé le fait que `SectionImage` était importé dans la page `/blog/lancement` alors que ce composant n'est pas utilisé.
=> Suppression d'un import non utilisé

components/event-carousel.js, pages/index.js
- Suppression du background blanc au hover des boutons de contrôle du slider d'événements.
- Changement du nom de style pour le bouton menant à la page `evenements` sur la page d'accueil.
=> Correction de style sur les boutons

components/meta.js
La balise `<title />`  dans le composant `<Head />` de **Next.js** ne chargeait pas en priorité le contenu de la props `title`.
La création de la balise et de son contenu était conditionnée suivant la présence ou non d'un titre passé dans le layout de la page (`main.js`).
La solution était de plutôt conditionner seulement le contenu de la balise `<title />`
=> Correction de l'affichage du titre de la page (meta)

components/button.js
La balise `<button />` servant à rediriger vers une page interne ou externe est modifié en faveur des balises `<a />` et `<Link />`
La balise `<a />` conserve les mêmes noms de classe du DSFR que pour le composant bouton afin que le style reste identique.
=> Utiliser des liens au lieu de boutons

pages/evenements.js
Correction d'une erreur de type faussant le filtrage des événements à venir.
**### AVANT**
**### APRÈS**
=> Correction de l'affichage des évents à venir

server/index.js
Ajout d'un espace entre l'url et le point d'exclamation afin d'éviter de fausser l'url affichée dans le log
```
server.listen(port, () => {
console.log(`Go to http://localhost:${port}!`)
})
```
devient
```
server.listen(port, () => {
console.log(`Go to http://localhost:${port} !`)
})
```
=> Correction de l'url du serveur dans les log

components/date-input.js, components/number-input.js, components/select-input.js, components/text-input.js
Cette PR ajoute 4 composants réutilisables: 
Input de type `text`
Input de type `number`
Input de type `select`
Input de type `date`
Ce composant accepte les props suivantes : 
- `label`: < string > Nom visible de l'input -  _required_
- `value`: < string > Valeur de l'input  (chaine de caractère vide par défaut)
- `name`: < string > Nom de l'input (accessibilité) - _required_
- `placeholder`: < string > Placeholder de l'input (vide par défault)
- `errorMessage`: < string > Message d'erreur passé par le composant parent
- `description`: < string > Affiche des indications supplémentaires concernant l'input
- `isRequired`: < boolean > Rend l'input `required`
- `isDisable`: < boolean > Rend l'input `disable`
- `onValueChange`: < function > Récupère et traite `event` - _required_
Ce composant …
=> Ajout de composant inputs

components/button.js
Le composant `<Button />` est modifié afin de :
- Donner la possibilité de définir un type `submit` || `button` (default)
- Donner la possibilité de désactiver l'interactivité du bouton.
- Donner la possibilité d'ajouter une icône au bouton, sur la gauche ou sur la droite.
Ce composant accepte les nouvelles props suivantes :
`icon` : < string > icône remixicon (ex : `success-fill`)
`iconSide` : < string > position d'affichage de l'icône - `left` (default) || `right`
`isDisabled` : < book > activer ou désactiver le bouton
=> Amélioration du composant <Button />

components/header.js
L'intégration de la barre de navigation dans le header a révélé un souci d'affichage du menu lors du passage en version mobile. 
Le bouton permettant l'ouverture du menu n'est pas trigger au clic dû à un souci d'intégration de l'API Javascript du DSFR dans un projet Next.js.
L'ouverture de ce menu est donc géré "manuellement" grâce une state permettant de déclencher l'ouverture/fermeture de la modale. Le css reproduit le plus fidèlement possible celui du DSFR.
=> Correction du header en version mobile

lib/__tests__/projets-validator.js, lib/projets-validator.js
En raison d'une anomalie avec la fonction `parse` de `date-fns` le pattern `YYYY-MM-DD` n'était pas strictement respecté.
En effet la date `10-10-10` était acceptée.
Cette PR ajout un cas de test litigieux et reprend l'implémentation de la validation des dates simples.
https://github.com/date-fns/date-fns/issues/3364
=> Rejet des dates de type YY-MM-DD

components/map-sidebar/contact.js, components/map-sidebar/pcrs-infos.js, layouts/map.js
Cette PR corrige un problème de bouton sur Safari, ainsi que deux problèmes mineurs.
- Sous Safari, le bouton permettant d'ouvrir / fermer le panneau latéral ne s'affichait pas
- Le message "Afficher la liste des acteurs" restait affiché lorsque le panneau était ouvert
- Suppression du tiret sur "non renseigné"
=> Corrige le problème de bouton de la sidebar sous Safari + problèmes mineurs

lib/__tests__/projets-validator.js, lib/projets-validator.js
Cette PR mets à jour le schéma de validation des projets afin de pouvoir ajouter le formulaire de création de projet.
- Mise à jour du champ `avancement`
- Ajout de la possibilité d’envoyer une valeur `null` sur les champs qui ne sont pas obligatoires
- Mise à jour des tests : 
- Modification du schéma invalide
- Ajout de tests pour la fonction `validatePerimetre` 
- Mise à jour des tests pour la fonction `validateCreation`
- Mise à jour des tests pour la fonction `validateChanges`
=> Mise à jour de la validation et des tests

data/herault-montpellier-2022-vecteur.yaml, scripts/migration-projets.js
Cette PR ajoute un script de migration qui permet de transférer les fichiers projets au format YAML vers la base de données MongoDB.
- Ajout du script de migration
- Correction d’un nom de projet en doublon
=> Ajout du script de migration des projets yaml vers la base de donnée

components/modal.js
Ce composant est réutilisable et permet l'apparition d'une boite de dialogue
Props : 
- `title` : titre de la modale 
- `children` : contenu de la modale
- `onClose` : <required> fonction de fermeture de la modale
La modale se ferme en utilisant le bouton fermer ou en cliquant en dehors de la modale
=> Ajout d'un composant modale 

pages/evenements.js
La page `/evenements` affichait les événements du mois ainsi que ceux, plus lointain, à venir.
À présent, l'utilisateur peut consulter les événements séparés en deux sections : ceux à venir (toutes dates confondues) et ceux passés.
----------------------------------------------
=> Affichage des événements passés

components/map-sidebar/project-header.js
Cette PR propose de masquer les boutons d’édition et de suppression, présents dans l’en-tête du panneau latéral de suivi des PCRS, si l’utilisateur n’a pas de jeton d’authentification dans son `LocalStorage`.
=> Masque les boutons édition / suppression dans la panneau latéral du suivi PCRS

components/map/map.js
Cette PR ajoute un bouton, sur la carte de suivi des PCRS, permettant d’accéder au formulaire.
Le bouton est affiché uniquement lorsque l’utilisateur a entré son jeton.
Fix #142
=> Ajout d’un lien vers le formulaire sur la carte de suivi

components/suivi-form/acteurs/index.js, components/text-input.js
La validation du numéro siren se faisant uniquement lorsque l’utilisateur entrait un code siren, le remplissage automatique ne modifiait pas la variable (`isSirenValid`).
_**Ceci est un "quickfix", il serait préférable de revoir la gestion des erreurs.**_
- Ajout des événements `onFocus` et `onBlur` sur le composant `inputText`
- Ajout du code siren dans la validation `isFormComplete`
- Modification du moment de vérification du code siren
Fix #140
=> Corrige le problème de validation du code siren

components/suivi-form/edit-form.js, pages/formulaire-suivi/index.js
Lorsque l'utilisateur se trouve sur la page d'édition ou de création de suivi de projet **sans avoir enregistré de token**, le bouton de fermeture de la modale d'authentification ne génère aucun effet.
Cette PR redirige l'utilisateur vers la page de la carte des suivis si celui-ci referme la modale avant d'avoir enregistré un token valide.
https://user-images.githubusercontent.com/66621960/231211296-86914fb6-0a70-4184-b5cc-407b562babdf.mov
Close #145
=> Gestion de la fermeture de la modal d'authentification

components/map-sidebar/index.js, server/projets.js
Si la date de début d'une étape et dans le futur, le projet l'affichera comme étant l'étape courante.
Cette PR corrige cette erreur et affiche l'étape antérieure à la date du jour comme étant l'étape en cours.
Close #151
=> Anticipation sur les dates sur la carte de suivi 

components/suivi-form/perimetres/index.js
Dans l'auto-complete du formulaire, section territoires, les identifiants des résultats proposés sont affichés afin de discriminer les éventuels doublons.
Close #154
=> Affichage les identifiants des territoires

components/map-sidebar/index.js, lib/suivi-pcrs.js, server/projets.js
Certains projets PCRS provenant des fichiers YAML, utilisés avant la mise en place de la base de données, ne possèdent pas de date sur le champ étapes.
La récente mise à jour de la gestion de date des étapes (PR #151) ayant modifié la façon d'afficher les étapes (affichage basé sur la date de l'étape au lieu du statut), les étapes des projets concernés étaient affichés en état "investigation" au lieu de "livré".
Cette PR ajoute une vérification de la présence des dates afin de déterminer quelle étape et couleur doivent être affichées dans le panneau latéral et sur la carte.
=> Correction de l'affichage des etapes de projets sans date

lib/suivi-pcrs.js, server/projets.js
Cette PR corrige un bug qui fait planter l'application lorsqu'un projet en statut investigation possède une date postérieure à aujourd'hui.
=> Corrige un problème avec les projets futurs

components/map-sidebar/index.js, components/map-sidebar/project-header.js, components/map/map.js, components/map/popup.js, layouts/map.js, pages/suivi-pcrs.js
Il peut arriver qu’un territoire soit couvert par plusieurs projets PCRS.
Actuellement, on ne peut afficher les détails que pour le projet le plus récent.
- Ajout d'un message dans la fenêtre contextuelle de la carte qui indique que le projet survolé possède plusieurs projets PCRS.
- Ajout d'un sélecteur dans l'en tête du panneau latéral permettant de sélectionner les projets.
=> Suivi-projet : Gestion des projets superposés

lib/__tests__/projets-validator.js, lib/projets-validator.js, scripts/migration-v03.js, server/__tests__/projets.js
_**Cette PR ajoute un script de migration des données des projets PCRS vers le modèle en version 0.3**_
→ Si `diffusion: flux` on retourne : `{diffusion: 'wms', publication: 'ftp'}`   
→ Si `diffusion: 'telechargement'` on retourne : `{diffusion: null, publication: 'ftp'}`
- Nouveau champ dans `acteur.role` → `porteur`
- Nouveau champ dans `subventions` → `detr`
- Nouveau champ `livrables.publication` → valeurs : `'ftp', 'cloud', 'http', 'inexistante'`
- Nouvelles valeurs pour le champ `livrables.diffusion` → `'wms', 'wmts', 'tms'`
- Nouveau champ dans `livrables` → `date_livraison`
- Ajout d’un script qui modifie les valeurs dans la base de données
- Mise à jour de la validation des projets
- Mise à jour des tests
=> Migration vers le modèle v0.3

components/map-sidebar/pcrs-infos.js
⚠️ PR à merger une fois que la migration vers la V3 est effectuée.
Le passage à la V3 ajoute de nouvelles informations (requises ou non) concernant les livrables.
Cette PR permet d'afficher ces informations dans la tooltip du livrable lorsqu'elles sont disponibles.
Les 3 données qui sont affichées sont : 
- Le type de diffusion
- Le type de publication
- La date de livraison
=> Affichages des nouvelles données v3

server/projets.js
Au survol de la carte, la popup n’affichait pas les porteurs "non-APLC" après la migration vers la version 0.3 du modèle de projet.
Cette PR ajoute le rôle de "porteur" dans les features de la carte, permettant de corriger ce problème.
=> Corrige l’affichage de "porteur" dans la popup de la carte

pages/formulaire-suivi/index.js
Un `id` avait été oublié pour la section périmètre dans le formulaire de création de nouveau projet, bloquant le scroll vers l'erreur à la validation du formulaire
=> Correction du scroll vers l'erreur de périmètre

components/map-sidebar/contact.js
Dans le panneau latéral de la carte, dans la partie "contacts", lorsqu'un des champs n'est pas renseigné, le message "non renseigné" était cliquable.
Comme la valeur était `null`, le navigateur essaye d'ouvrir 'null'.
C'est à présent `undefined` la valeur par défaut en cas d'absence de données. Le lien passe automatiquement en `disabled`
------------------------------------------
Close #164
=> Désactiver les balises <a> lorsque les données sont indisponibles

components/suivi-form/acteurs/index.js
Lorsqu'un utilisateur choisissait le rôle d'un porteur de projet APLC pour un acteur, il lui était toujours possible de rajouter un acteur avec comme rôle porteur de projet non-aplc. Hors, un seul porteur de projet est autorisé.
Cette PR corrige ce problème en : 
- Permettant à l'utilisateur de modifier le rôle un acteur porteur de projet entre aplc/non-aplc
- Bloque le choix aplc/non-aplc pour les acteurs ajoutés si un de ces rôles est déjà associé à un acteur existant.
Acteur aplc/non-aplc ou acteur ajouté sans aucun porteur dans la liste des acteurs existants.
Nouvel acteur ajouté alors que le rôle de porteur aplc/non-aplc est déjà attribué
=> Gérer le rôle des porteurs de projet dans le sélecteur

components/suivi-form/index.js
Lorsque l'utilisateur se retrouve sur la page `/formulaire-suivi` et souhaite refermer la modale d'authentification s'il ne dispose pas de token, le bouton de fermeture de la modale n'effectue aucune action visible au clic.
Cette PR permet de rediriger l'utilisateur vers la page de la carte des suivis.
=> Redirection vers la carte de suivi à la fermeture de la modale d'authentification

server/projets.js
Actuellement, lorsque l'utilisateur entre un nom de projet déjà présent dans la base de données, le formulaire renvoi une erreur 500 sans explication.
Cette PR ajoute un `try / catch` permettant de récupérer l'erreur envoyé par MongoDB et d'envoyer une erreur `409` ainsi qu'un message d'erreur explicite.
Fix #168
=> Corrige l’erreur de conflit entre les noms de projet

README.md, lib/export/csv.js, lib/export/projet-csv.js, package.json, server/index.js, yarn.lock
Cette PR propose d’ajouter des routes permettant le téléchargement des données de suivi des PCRS au format CSV.
Les fichiers disponibles sont `projets.csv`, `livrables.csv`, `tours-de-tables.csv` et `subventions.csv`.
- Ajout de fonctions permettant la construction de fichier json et la conversion vers les champs attendus par le fichier CSV
- Ajout de route permettant de télécharger les données dans un fichier CSV
| Route | Type | Description |
|-------|------|-------------|
| `/data/projets.csv`| **GET** | *Retourne un fichier CSV contenant l’ensemble des projets PCRS* |
| `/data/livrables.csv`| **GET** | *Retourne un fichier CSV contenant l’ensemble des livrables des projets PCRS* |
| `/data/tours-de-table.csv`| **GET** | *Retourne un fichier CSV contenant l’ensemble des tours de table …
=> Ajout de routes permettant l'export de fichier CSV

components/suivi-form/livrables/livrable-form.js
Lorsqu'une erreur apparaissait sur la première ligne, on pouvait observer un décalage des champs par rapport aux autres.
**APRÈS**
=> Correction de l'alignement des champs livrables

components/date-input.js, package.json, yarn.lock
La mise à jour de la bibliothèque DSFR vers la version 1.9.2 corrige le problème d'icône calendrier sur les champs de type `date`
Close #143
=> Mise à jour de la bibliothèque DSFR

components/map-sidebar/project-header.js, components/suivi-form/delete-modal.js, components/suivi-form/index.js, styles/colors.js
Cette PR ajoute : 
- Des boutons de suppression de projet lorsque l'utilisateur est sur la page du formulaire en mode édition
- Un composant réutilisable `<DeleteModal />`, utilisé dans l'entête du projet dans la carte de suivi et dans la page du formulaire en mode édition. Ce composant reprend la structure de la modale de suppression déjà existante dans l'entête du projet et son design a bénéficié d'une amélioration.
----------------------------------
=> Amélioration de la suppression de projet

package.json, server/util/mongo.js
Cette PR ajoute l'option `sparse` sur l'index Mongo `editorKey`
=> Corrige le problème d'index `null` dans MongoDB

README.md, lib/export/csv.js, server/auth/middleware.js, server/index.js
Cette PR ajoute une route permettant aux administrateurs de récupérer l'ensemble des codes d'édition des projets dans un fichier CSV.
- Ajoute une fonction qui crée le fichier CSV
- Ajoute un middleware pour autoriser uniquement les administrateurs
- Ajoute une route pour récupérer le fichier CSV
- Mise à jour de la documentation
=> Ajout d'une route `/data/editor-keys.csv`

components/suivi-form/index.js, components/suivi-form/utils/payload-errors.js
Les erreurs concernant les champs problématiques renvoyés par l'API n'étaient pas traitées. Seule une erreur générale s'affichait, sans plus de précision.
Les erreurs principales sont interprétées afin d'apporter plus de clarté sur la cause de l'erreur d'envoi du formulaire.
=> Traitement des erreurs de payload

README.md, package.json, scripts/authorized-creators-emails.js, server/admin/creators-emails.js, server/auth/pin-code/index.js, server/index.js, server/util/mongo.js
Actuellement, les adresses mails des personnes autorisés à créer des projets PCRS sont hébergées sur un fichier externe accessible avec un simple lien.
Cette PR ajoute des routes, réservées à l’administration, permettant de gérer la liste des mails des personnes autorisées à créer des projets PCRS.
- Ajout des fonctions permettant de trouver/récupérer/modifier/supprimer une personne autorisée
- Ajout des routes GET/POST/PUT/DELETE
- Ajout d’un script pour migrer les adresses du fichier externe vers la nouvelle collection
- Mise à jour de la documentation
=> Ajoute une collection des mails autorisés à créer des projets PCRS

components/map-sidebar/project-header.js
Cette PR ajoute le lien d'édition du projet, en dessous du nom du projet, afin que les administrateurs aient plus facilement accès à cette information et puissent partager le lien sans avoir à ouvrir le formulaire.
- Affichage du lien dans le composant `project-header`
- Ajout d'une icône cliquable pour faciliter la copie du lien dans le presse-papier
Capture :
=> Ajout du lien d'édtion pour les administrateurs

components/gestion-admin/changes.js, lib/suivi-pcrs.js, pages/gestion-suivi.js
Cette PR ajoute l'affichage de la liste des projets triés par date de création / modification / suppression dans l'espace d'administration afin que les administrateurs puissent visualiser les modifications récentes effectuées sur le suivi des projets PCRS.
- Ajout d'un onglet pour afficher la liste
- Affichage de la liste dans un tableau
- Ajout d'un filtre pour chercher un projet
- Réduction des marges en version mobile
=> Affichage des projets triés par date de création / modification / suppression dans l'espace administrateur

components/map/layers/departement-fill-nature.json, components/map/legend.js, components/map/map-tool-box.js, components/map/map.js
Cette PR ajoute un layer ainsi qu'un filtre permettant d'ajuster la visualisation des données de suivi de la carte.
- Ajout d'un filtre permettant d'afficher uniquement les projets concernés par un porteur de projet donné.
- Ajout d'un layer permettant d'afficher les projets colorisés par "nature" (vecteur, raster ou mixte).
- Ajout d'une "boite à outils" pour afficher les nouvelles options sans masquer la carte.
Technique : 
- Création de fonction afin de simplifier les événements "onClick" et "onHover" de la carte.
- Suppression d'une partie de code qui n'était plus utilisée.
- Mise à jour de la légende.
=> Ajout de fonctionnalités sur la carte de suivi

components/suivi-form/index.js, pages/formulaire-suivi.js
La gestion de la récupération du code d'édition d'un projet était difficilement compréhensible.
Sur le composant du formulaire de suivi, la state `editCode` prend comme valeur initiale le code d'édition d'un projet si le formulaire contient les données à éditer (formulaire en "mode édition").
Dans le cas d'un formulaire vierge, `editCode` sera `null` par défaut et récupéré à la création du projet.
=> Amélioration de la compréhension de la récupération de code d'édition

components/map/legend.js
Les couleurs de la carte de suivi de projet ont été mises à jour avec la PR #225, mais la légende n'a pas été mise à jour.
Cette PR ajoute une nouvelle légende synchronisée avec les couleurs de la carte de suivi.
Fix #227 
Capture :
=> Mise à jour de la légende de la carte 

components/map-sidebar/project-header.js, components/suivi-form/delete-modal.js, components/suivi-form/index.js
Le composant `<DeleteModal />` recevait une prop nommée `token` mais qui pouvait être à la fois le token administrateur/créateur et le code d'édition. 
Ce nom rendait le code peu compréhensible. La prop est renommée `authorisationCode` pour plus de clarté.
=> Modification nom de props pour la modale d'authentification

components/footer.js, components/suivi-form/authentification/admin-authentification-modal.js, contexts/authentification-token.js, pages/gestion-suivi.js
Malgré la présence d'un token administrateur, la modale de connexion apparaissait quelques secondes le temps de la récupération du token.
Ce fix permet de n'afficher la modale d'authentification seulement une fois que toutes les données requises sont récupérées (token + rôle de l'utilisateur) et que cela est nécessaire.
https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/e57f49e2-00cf-4de1-8a99-c2f092ed887e
=> Correction de l'affichage de la modale de connexion

components/footer.js, components/suivi-form/authentification/admin-authentification-modal.js
"Accès administrateur" dans le `footer` redirige à présent vers la page `/gestion-suivi` au lieu d'ouvrir la modale d'authentification.
=> Ajout d'un point d'entrée vers la page administrateur

components/event-carousel.js
Le slider sur la page d'accueil faisant défiler les prochains événements dispose à présent d'un lien vers la page des événements.
=> Lien vers la page des événements dans le bandeau

components/suivi-form/index.js
À ce jour, la présence d'un porteur APLC ou d'un porteur non-APLC n'était pas requise à la validation du formulaire de suivi.
Or, il est obligatoire qu'un projet dispose d'un porteur.
Cette PR se concentre sur le blocage de la validation du formulaire et sur la gestion d'erreur en front dans le cas où est porteur n'a pas été ajouté.
À terme, cette vérification devra s'effectuer via le validateur.
Close  #222
=> Imposer la présence d'un acteur porteur

components/hero.js
Le lien "prendre contact" dans le hero de la page d'accueil ne fonctionnait pas. 
À présent, il redirige correctement vers la section contact.
=> Correction de l'ancre de la section contact

styles/pcrs-data-colors.js
L'acteur de type `porteur` ne bénéficiait pas d'une couleur afin de le distinguer dans la liste des acteurs dans la sidebar (page `/suivi-pcrs`)
=> Ajout de la couleur définissant le porteur

components/autocomplete-input.js, components/autocomplete-render-item.js
La largeur du menu du composant `<Autocomplete />` s'adaptait à la taille de l'élément le plus grand.
La largeur s'adapte à présent à celle de l'input
=> Adaptation de la largeur des items dans le composants <Autocomplete />

lib/__tests__/projets-validator.js, lib/projets-validator.js, server/__tests__/projets.js
Cette PR ajoute une fonction permettant la validation de l'ordre des dates des étapes de projet.
Elle permet d'éviter que l'utilisateur entre une date ultérieure à la précédente étapes.
- Ajout de la fonction `validateEtapesDates`
- Ajout de tests pour cette fonction
=> Validation de l'ordre des dates des étapes des projets

components/suivi-form/index.js, components/suivi-form/utils/payload-errors.js
⚠️ À merger avec la PR Validation de l'ordre des dates des étapes des projets [#244 ](https://github.com/openpcrs/pcrs.beta.gouv.fr/pull/244) (partie back, gestion via le validateur)
Cette PR constitue la partie front de la problématique évoquée dans l'issue [Evaluer la cohérence des dates du calendrier du formulaire #238 ](https://github.com/openpcrs/pcrs.beta.gouv.fr/pull/244). Permet l'interprétation et l'affichage d'un message d'erreur compréhensible par l'utilisateur en cas d'erreur dans l'ordre des dates des étapes dans le formulaire de suivi du PCRS.
=> Gestion du message d'erreur pour les étapes (formulaire de suivi)

components/gestion-admin/header.js, components/gestion-admin/porteurs.js, components/gestion-admin/utils/index.js, lib/string.js
Dans la page de gestion de suivi, les porteurs peuvent être triés par ordre alphabétique ascendant.
Il a été remarqué que la fonction était sensible à la casse et qu'un nom en majuscule sera trié avant un nom en minuscule malgré l'ordre des premières lettres dans l'alphabet.
Close #258
=> Fonction de tri insensible à la casse

components/gestion-admin/add-form.js, components/gestion-admin/header.js, components/gestion-admin/porteurs.js
La fonction permettant d'ajouter un porteur dans la base de données se trouvait dans le composant `/gestion-admin/header.js` qui sera partagé avec la gestion des administrateurs.
Cette fonction est à présent passée en prop (`onAdd`) dans `<Header />`
=> Déplacer la fonction d'ajout de porteurs

components/map/map-tool-box.js, layouts/map.js
Cette PR corrige un problème de superposition des éléments sur la carte.
En version mobile, le bouton "Ajouter un projet" était placé au-dessus de la boite à outils lorsque celle-ci était ouverte.
- Ajout d’un `z-index: 2` sur le composant `MapToolBox`
=> Corrige un problème de superposition du bouton et de la boite à outils de la carte

components/autocomplete-input.js
Cette PR corrige une erreur de `props` affichée en console.
Cette erreur venait d’une propriété `required` qui n'était pas utilisée.
Fix #261
=> Corrige une erreur dans la console

components/map/map-tool-box.js
Cette PR passe le fond de la boite à outils de carte de suivi en blanc afin d'homogénéiser le visuel avec le composant `Autocomplete`.
=> Suppression du fond semi-transparent sur la boite à outils de la carte de suivi

components/gestion-admin/add-form.js, components/gestion-admin/administrateur-list.js, components/gestion-admin/administrateurs.js, components/gestion-admin/header.js, components/gestion-admin/list-item.js, components/gestion-admin/porteur-list.js, components/gestion-admin/porteurs.js, hooks/errors.js, lib/suivi-pcrs.js, pages/gestion-suivi.js
**⚠️ Ne pas merger avant la PR Ajout d’une API pour la gestion des administrateurs [#253 ](https://github.com/openpcrs/pcrs.beta.gouv.fr/pull/253)**
La page `/gestion-suivi` permet à présent d'afficher la liste des administrateurs et de les gérer.
Au même titre que pour les porteurs, il est possible : 
- De rajouter un administrateur
- De supprimer un administrateur (autre que soit-même)
- De consulter les administrateurs actifs, les rechercher via une barre de recherche et trier leur ordre d'apparition.
L'utilisateur identifié se verra apparaitre dans la liste avec une icône différente.
------------------------
------------------------
=> Ajout de la gestion des administrateurs 

lib/suivi-pcrs.js, server/index.js, server/routes/admin.js, server/routes/administrators.js, server/routes/auth.js, server/routes/creators-emails.js, server/routes/data.js, server/routes/projets.js, server/routes/report.js
Cette PR exporte les routes dans des fichiers séparés afin d'alléger le fichier `server/index.js` qui commençait à être long.
Cette modification permettra également de tester les routes.
- Création d’un dossier `routes` 
- Création des fichiers contenant les routes : 
- - `routes/admin.js`
- - `routes/auth.js`
- - `routes/data.js`
- - `routes/projets.js`
- Mise à jour du fichier `server/index.js`
=> Export des routes dans différents fichiers

package.json, server/__tests__/index.js, server/mock/mock-invalid-projet.js, server/mock/mock-valid-projet.js, yarn.lock
Cette PR ajoute des tests sur les routes de l’API.
- Installation de `supertest`
- Ajouts des mocks de projet (valide et invalide)
- Tests sur les routes : 
- - `/projets`
- - `/auth`
- - `/creators-emails`
- - `/administrators`
- - `/report`
=> Tests sur les routes de l’API

server/admin/administrators.js, server/admin/creators-emails.js
Cette PR corrige le message d’erreur renvoyé par l’API lorsque l’utilisateur veut modifier un administrateur ou un porteur avec une adresse mail déjà présente dans la base de données.
=> Corrige le message d’erreur du PUT de les routes `/administrators` et `/creators-emails`

pages/calculatrice.js
Sur la page `/calculatrice`, la recherche par territoire de type "EPCI" fait planter le site.
Le problème venait de l'appel à l'API : 
Lorsque l'URL est construite, nous ajoutons un "S" au type de territoire afin d'appeler l'index correct. 
Or, l'index pour les EPCI est bien "epci" et non "epciS". ([ref](https://github.com/openpcrs/pcrs.beta.gouv.fr/blob/c0542b225724bcc5102e755194ed10481c66db3e/lib/territoires.js#L50))
Cette PR ajoute une condition afin d'éviter d'ajouter un "s" lorsque le territoire est de type epci.
EDIT : 
Cette PR est une correction rapide pour contourner un problème plus compliqué à régler.
Une issue a été ouverte [ici](https://github.com/openpcrs/pcrs.beta.gouv.fr/issues/285)
=> [[QuickFix]] Corrige la recherche par EPCI de la calculatrice

server/admin/__tests__/administrators.js, server/admin/__tests__/creators-emails.js, server/admin/administrators.js, server/admin/creators-emails.js
En testant la PR #283, j'ai remarqué que l’API ne vérifie pas la validité de l’adresse mail lors de l’édition de celle-ci.
Cette PR ajoute cette vérification de la même façon que pour les administrateurs.
=> Ajout de la vérification de l’adresse email lors de l'édition d’un porteur de projet

lib/suivi-pcrs.js, pages/formulaire-suivi.js
Suite à une mise à jour de la gestion des variables d’environnement, une erreur 500 était lancée lorsque l’utilisateur utilisait le lien d’édition d’un projet.
Cette PR enlève un `getInitialProps` pour utiliser un simple `useEffect` et corrige une URL relative.
=> Corrige une erreur 500 sur les liens d’édition

pages/formulaire-suivi.js
Depuis la dernière PR, il n'est plus possible de créer un formulaire. Une page vierge est renvoyé quand aucun projet n’est trouvé, empêchant la création d’un nouveau.
Un chargement a été ajouté à la page, le temps que le projet soit récupéré s'il est passé en paramètre. Le formulaire est renvoyé même sans projet afin de pouvoir faire une création.
=> Ajout d'un chargement à la page /suivi-formulaire

pages/formulaire-suivi.js
Jusqu'à présent, la validité du code d'édition passé en `query` dans la page du formulaire de suivi n'était pas vérifiée. De ce fait, un code d'édition périmé permettait encore d'accéder à l'édition du formulaire
Fix #295 
-----------------------------------
- Ajout du code d'édition en tant que `token` à la fonction `getProject`. La vérification s'effectue ainsi en amont et une erreur `403` est automatiquement retournée en cas d'échec d'authentification dû à la non-correspondance du code entré et du code rattaché au projet.
- Le message d'erreur donnant la raison du blocage au formulaire est affiché au lieu du code afin d'ajouter de la compréhension et facilité la gestion des codes d'erreur en front
=> Vérification de la validité du code d'édition

lib/suivi-pcrs.js
La méthode de la fonction `resetEditCode` était erronée, menant à une erreur `404` au moment de la réédition du code d'édition.
Changer la méthode `POST` en `GET`
=> Correction de la réédition du code d'édition

components/suivi-form/acteurs/acteur-form.js, components/suivi-form/acteurs/actors-autocomplete-input.js
Création d'un composant `<ActorsAutocompleteInput />` comprenant toute la gestion d'autocomplete lors de la recherche d'un acteur.
Cette création de composant offre une possibilité de réutilisation du composant tout en allégeant le composant `<ActorForm />`
Props reçues : 
`inputValue`: la valeur du champ
`inputError`:  le message d'erreur à afficher, limité à l'input (ex : "champs vide")
`onValueChange`: fonction de modification de la valeur du champ
`onSelectValue`: fonction de sélection de la valeur dans la liste de proposition
=> Création d'un composant de recherche d'acteur

components/suivi-form/acteurs/actors-autocomplete-input.js
Le composant `ActorsAutocompleteInput` permet d'afficher les acteurs ainsi que leur secteur d'activité principale (`section_activite_principale`). Or cette activité peut être non définie et affiche donc `undefined`
Afficher la valeur "N/A" en cas de valeur nulle afin d'avertir l'utilisateur que cette information n'a pas été renseignée
Close  #306
=> [FIX] "section_activite_principale" peut être nul 

components/event-card.js, events.json
- Ajout d'un évènement
- Correctif des cartes événements lorsque le titre est long :
=> Ajout evenement diffusion 12/10

components/number-input.js
Lorsque l'on utilise un champ `<NumberInput />` alors que `min` ou `max` n'est pas défini, alors la validation du champ ne se fait pas correctement est l'erreur `La valeur doit être comprise entre 0 et null` s’affiche.
Cette erreur s’affiche, car la valeur `null` est donnée par défaut à `min` et `max` via `defaultProps` lorsqu'ils ne sont pas définis. Or la méthode `handleRangeError` s'attend à avoir des `undefined`.
Cette PR retire l'attribution de valeur pas défaut à `min` et `max` dans `<NumberInput/>`.
=> Correction de la validation d’erreur d'un champ nombre

components/suivi-form/index.js, components/suivi-form/perimetres/index.js, components/suivi-form/perimetres/perimetre-form.js, components/suivi-form/perimetres/perimetre.js, hooks/input.js
Le code des composants du formulaire de périmètres souffre de quelques erreurs de conception et est assez complexe à maintenir.
Cette PR corrige les différents problèmes du composant et supprime l'édition pour simplifier son usage et son code.
Le fonctionnement de ce formulaire a également été modifié, afin de rester affiché et permettre l'ajout de plusieurs périmètres les uns à la suite des autres.
https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/7040549/26eadd41-5696-4617-b313-0b0556dc6c82
Le `hook` `useInput` peut maintenant détecter si un champ a été utilisé pour ne pas renvoyer de message d'erreur si le champ est requis et vide à l'initialisation. De plus, une méthode de "reset" a été ajouté afin de réinitialiser complètement l'input à la demande.
=> Reprise du formulaire de périmètres 

components/number-input.js, components/suivi-form/subventions/index.js, components/suivi-form/subventions/subvention-card.js, components/suivi-form/subventions/subvention-form.js, lib/string.js
Le code des composants du formulaire des subventions souffre de quelques erreurs de conception et est assez complexe à maintenir.
Cette PR corrige :
- les différents problèmes du composant (notamment la gestion compliquée de l'ajout et la modification d'une subvention)
- Format le montant en euros
Le composant `<NumberInput/>` force désormais le type d'input à `number`, puisque c'est le rôle de ce composant.
=> Reprise du formulaire des subventions

backend/lib/projets-validator.js, scripts/migration-v04.js
La migration ne prend pas en compte les nouveaux champs `prod_en_cours` et `convention_signee`.
Les champs `crs`, `compression`, `publication` ne sont plus pris en charge.
Cette PR ajoute une fonction qui ajoute les champs `prod_en_cours` et `convention_signee` aux statuts des étapes comportant un champ `prod_en_cours`.
Elle ajoute également un champ `date_debut` initialisé à `null`.
La suppression des champs non utilisés a été ajoutée.
Une tolérance sur les champs inconnus a été ajoutée afin de ne pas casser la compatibilité avec le modèle précédent.
=> Mises à jour du script de migration vers le modèle v0.4

backend/export/csv.js
Cette PR modifie le format de l’export de fichier CSV pour correspondre au modèle v0.4 : 
- Modifications et ajouts sur les champs des statuts de projets
- Modifications et ajouts sur les champs des livrables (les champs supprimés restent vides pour le moment, ils seront supprimés dans une prochaine version)
- Passage au `snake_case` pour tous les champs
=> Modification du modèle d’export CSV

backend/lib/api-scanner.js, backend/routes/projets.js
Cette PR ajoute une route permettant de récupérer un jeton autorisant à télécharger une tuile depuis un stockage publique.
- Ajout d’une fonction pour demander un jeton au scanner
- Ajout d’une route qui vérifie que le téléchargement est possible puis renvoie le jeton.
=> Ajout d’une route pour récupére un jeton de téléchargement de tuiles

components/projet/index.js, components/projet/livrables-section.js, components/projet/scanned-data.js, components/projet/scanner-map.js, components/projet/stockage-preview.js, lib/suivi-pcrs.js
Cette PR ajout la possibilité de télécharger les données d'une dalle issue du stockage d’un livrable.
Lorsque la donnée est disponible, il est possible de cliquer sur une tuile afin de la télécharger. Une bulle d’information a été ajoutée au popup qui s'affiche au survol.
Le middleware `ensureIsAdmin` a été retiré de la route `/:projetId/stockages/:stockageId/generate-download-token` afin de la rendre accessible à tous.
=> Téléchargement des données issues d'un stockage

components/projet/livrables-section.js
- La sélection du livrable est corrigé
- Le label du sélecteur affiche désormais le nom du livrable par défaut
- L’affichage du composant `<StockagePreview>` n'est possible que si un stockage existe sur le livrable choisi
=> Correction de la sélection du livrable

pages/projet/[id].js
Les metas de la page se trouvait sur la page d'erreur renvoyée.
- Modification des erreurs de la page renvoyant l'erreur
- Ajout des metas de la page projet
=> Ajout des méta de la page projet

components/suivi-form/livrables/stockage-card.js, components/suivi-form/livrables/stockage-form/ftp-params-inputs.js, components/suivi-form/livrables/stockage-form/http-params-inputs.js, components/suivi-form/livrables/stockage-form/sftp-params-inputs.js, lib/utils/projet.js
Création d'un lexique réutilisable pour les paramètres d'un stockage.
- `host` : 'Nom d’hôte du service'
- `username` : 'Nom d’utilisateur'
- `password` : 'Mot de passe'
- `startPath` : 'Chemin du répertoire'
- `port` : 'Port d’accès au service
- `url` : 'URL du stockage'
- `secure` : 'Connexion sécurisée'
=> Mise à jour des labels utilisés pour le stockage

components/containers/dropdown-list.js
Lorsque le composant `Dropdown` est ouvert, le clic sur le contenu enfant ferme le composant.
Cette PR déplace l’événement `onClick` sur la partie supérieure afin d’éviter la fermeture lors du clic à l’intérieur de la partie "masquable"
Fix #354
=> Corrige le clic dans les paramètres de stockage

components/suivi-form/livrables/livrable-form.js, components/suivi-form/livrables/stockage-card.js, components/suivi-form/livrables/stockage-form/http-params-inputs.js, components/suivi-form/livrables/stockage-form/index.js
Actuellement, il n’est pas possible d’éditer un stockage sur un livrable.
Le stockage doit être supprimé puis recréé par l’utilisateur.
Cette PR ajoute la possibilité d’éditer le stockage d’un livrable.
Fix #359
=> Edition du stockage de livrable

components/suivi-form/livrables/stockage-form/ftp-params-inputs.js, components/suivi-form/livrables/stockage-form/sftp-params-inputs.js
Cette PR modifie l'affichage des champs "port" et "host" afin que ceux-ci soient présentés sur une seule ligne.
Fix #360 
Capture : 
Avant : 
Après :
=> Passage de "host" et "port" sur la même ligne pour les stockages FTP/SFTP

backend/lib/api-scanner.js, backend/routes/projets.js, components/suivi-form/index.js, components/suivi-form/livrables/index.js, components/suivi-form/livrables/livrable-card.js, components/suivi-form/livrables/stockage-refresh.js, lib/suivi-pcrs.js, lib/utils/request.js
Cette PR ajoute un bouton permettant de relancer le scan d’un stockage : 
- Ajout d'une fonction qui appelle le scanner en lui fournissant le jeton d'authentification
- Ajout d'une route `/projets/:projetId/stockages/:stockageId/refresh-scan`
- Ajout d'une fonction qui appelle la route `/projets/:projetId/stockages/:stockageId/refresh-scan`
- Ajout d'un bouton dans le formulaire permettant de relancer le scan de stockage
Fix #363
=> Ajout d’un bouton pour relancer le scan d’un stockage

components/suivi-form/index.js
Cette PR ajoute un message d’information dans le formulaire de suivi, afin d’indiquer aux utilisateurs qu’ils doivent ajouter les étapes suite à la mise à jour du modèle de données PCRS.
Fix #365
=> Ajout d’un message d’information dans le formulaire de suivi

components/projet/list-render-items.js
Cette demande d'ajout corrige un problème lié à l'affichage du stockage d'un projet.
Un des composants était hydraté par un objet alors que celui-ci attendait une chaine de caractère.
=> Correction d'un problème empéchant l'affichage d'un projet avec stockage

components/suivi-form/livrables/stockage-card.js
Modification mineure pour retirer l'affichage de la longueur des mots de passe et des noms d'utilisateurs hors formulaire d'édition.
Fix #404
=> Modification de l'affichage mots de passe dans le formulaire

lib/entreprises-api.js
Cette pull request ajoute un identifiant dans l'URL de l'API Entreprises, afin d'identifier plus finement les appels provenant de notre site.
> _La variable d’environnement n’est pas utilisée en production. Cette modification devrait donc suffire_
Fix #415
=> Ajout d'une info dans l'URL de l'API Entreprises

components/map-sidebar/index.js, components/map-sidebar/project-header.js, components/map/index.js, components/map/styles/vector.json, layouts/suivi-pcrs-map-layout/index.js, pages/suivi-pcrs.js
Cette pull request corrige la superposition des projets lorsqu’ils sont sélectionnés, comme décrit dans cette [issue](https://github.com/openpcrs/pcrs.beta.gouv.fr/issues/399).
- Modification de l'affichage du projet sélectionné : 
Précédemment, pour afficher un projet sélectionné, nous modifions la transparence de la couleur du projet. Désormais, c’est un nouveau layer qui est superposé sur le layer de couleur, permettant de masquer les projets contenus dans un projet sélectionné.
- Ajout d’un bouton permettant de fermer la sélection d’un projet
Fix #399
=> Corrige la superposition des projets PCRS

backend/lib/projets-validator.js
Dans la pull request #412, nous avons oublié d’ajouter DXF dans la partie `livrablesSchemaUpdate` empêchant la modification d’un projet contenant un livrable de nature "DXF".
Cette pull request ajoute ce champ pour corriger le problème.
=> Corrige un oubli lors de l'ajout de DXF

components/gestion-admin/changes.js
Récemment un projet a été créé avec le nom "PCRS ". Nous avons eu des difficultés à retrouver le projet en question sur la carte de suivi.
Cette PR ajoute un lien sur le nom du projet dans la liste des projets modifié, permettant d’accéder rapidement à la page du projet.
=> Ajoute un lien sur le nom du projet dans la partie gestion

package.json
Cette PR supprime la commande qui lance le script de migration au démarrage de l'application sur Scalingo
=> Supprime le lancement du script de migration au build 

pages/mentions-legales.js
Suppression du passage des données personnelles (sera prochainement remplacé après proposition du service juridique) et mise à jour du nom de l'éditeur.
=> Mise à jour mentions légales

backend/lib/projets-validator.js, components/suivi-form/livrables/utils/select-options.js, lib/utils/projet.js
Nous avions besoin des valeurs supplémentaires dans le formulaire
Natures de livrables :
- DWG Autocad vecteur
Modes de diffusion :
- Aucune diffusion
Vu #419 pour éviter les oublis dans le valideur
=> Ajout de valeurs diffusion et livrables pour le formulaire

components/suivi-form/livrables/stockage-form/index.js
Il semble que des espaces dans les paramètres de connexion aux stockages des livrables puissent poser un problème lors du scan de celui-ci.
Cette pull request ajoute une fonction permettant de supprimer les espaces autour des valeurs des paramètres de stockage d’un livrable.
=> Supprime les espaces autour des valeurs de stockage de livrables

components/projet/scan-result.js, components/suivi-form/livrables/livrable-card.js
Cette PR modifie l’affichage du message sous le bouton pour relancer le scan.
Avant : 
Après :
=> Corrige l'affichage du message dans les livrables

README.md, backend/export/csv.js, backend/routes/data.js
Cette PR ajoute une route permettant de télécharger un export CSV de la liste des territoires.
Extrait du fichier exporté : 
```csv
ref_projet,nature_territoire,reference
64281c3f4340ffbf17bf2de0,departement,08
64281c3f4340ffbf17bf2de2,departement,09
64281c3f4340ffbf17bf2de4,departement,10
64281c3f4340ffbf17bf2de6,epci,200067874
64281c3f4340ffbf17bf2de8,epci,200067874
64281c3f4340ffbf17bf2dea,epci,200067783
64281c3f4340ffbf17bf2dec,epci,246700488
64281c3f4340ffbf17bf2dee,epci,200069052
``` 
Détails : 
-  Création fonction `exportTerritoires`
- Ajout de la route `data/territoires.csv`
- Mise à jour du README
Fix #456
=> Export de territoires.csv
