incubateur-territoires/pcrs.beta.gouv.fr

- layouts/meta.js
Utiliser `summary_large_image` au lieu de `summary`
> Corriger meta twitter (image)

- layouts/meta.js
- Correction des url vers les images
- Placer les meta Twitter sous Open Graph meta
> Correction de l'affichage des images de préview

- pages/index.js
Modifications du texte plus raccord avec l'état actuel de la carto sur le site
> Reformulation suivi carto

- .github/workflows/node.js.yml
Cette pull-request ajoute une action github afin de profiter de contrôles supplémentaires avant de merger.
> Ajout d’un workflow NodeJs

- .eslintrc
- pages/_app.js
- pages/evenements.js
Cette PR corrige l'importation des icônes du dsfr qui empêche le déploiement de l'application.
Elle supprime également un fichier non utilisé
> Corrige le problème de déploiement

- components/blog/blog-card.js
- components/blog/blog-pagination.js
- components/blog/blog-tags.js
- components/blog/post.js
- components/button.js
- components/event-card.js
- components/event-carousel.js
- components/follow.js
- components/header.js
- components/hero.js
- components/section-image.js
- components/section.js
- layouts/main.js
- lib/blog.js
- next.config.js
- package.json
- pages/404.js
- pages/500.js
- pages/blog/[slug].js
- pages/blog/index.js
- pages/declaration-accessibilite.js
- pages/evenements.js
- pages/index.js
- pages/mentions-legales.js
- styles/colors.js
Cette PR mets à jour les règles de [XO](https://github.com/xojs/xo).
Liste des règles supprimées : 
- `"unicorn/catch-error-name": "off"`
- `"react/jsx-sort-props": "off"`
- `"import/no-anonymous-default-export": "off"`
- `"n/prefer-global/process": "off"`
- `"unicorn/prefer-node-protocol": "off"`
- `"import/extensions": "off"`
> Mise à jour de la configuration de XO

- data/craig-allier.yaml
- data/craig-cantal.yaml
- data/craig-hauteloire.yaml
- data/craig-puyDome.yaml
- data/craig-stetienne.yaml
- data/craig-valence.yaml
- data/sde07-complement.yaml
- data/sde07-principal.yaml
- data/siel42-loire.yaml
Ajouts de plusieurs projets en AUvergne Rhône-Alpes
> Ajout des projets Auvergne, Ardèche, Loire et Drôme

- package.json
- server/index.js
- yarn.lock
Configuration "Custom server" pour Next.js en vue de la mise en place du service de tuiles pour le suivi du PCRS.
> Mise en place du serveur Express

- lib/build-geometry.js
- lib/date-utils.js
- package.json
- yarn.lock
Utilisation des données `contours-administratifs` Etalab en résolution 50m
> Ajout d'un constructeur de géométries à partir d'une liste de territoires

- data/drome-principal.yaml
- data/rhone-principal.yaml
- data/sde07-principal.yaml
- data/sded-principal.yaml
- data/siea-2019.yaml
- data/syane-rural.yaml
@GllmR Il y a dans ce fix deux projets qui n'ont pas d'acteurs, dont nous ignorons presque tout.
Est-ce que cela pose problème pour tes traitements ?
> Fix projets Auvergne-Rhone-Alpes

- scripts/build-data.js
- Ajout de `montant` et `echeance` au champ "subventions"
- Ajout de champs obligatoires
> Corrige et mets à jour le schéma de validation des projets PCRS

- components/number-input.js
- components/text-input.js
Suppression du margin top lors de l'affichage optionnel de la `description` dans les composants `InputText` et `NumberText`
> Correction du margin de la description dans l'input text et number

- lib/entreprises-api.js
- lib/http-error.js
- package.json
Ajout d'un fichier permettant une recherche d'entreprises par nom via l'api REST `recherche-entreprises.api.gouv.fr`.
Une class globale de gestions d'erreurs lors de la recherche est également ajoutée.
> Ajout de la recherche d'entreprise par nom

- data/basrhin-haguenau-2019.yaml
- data/basrhin-haguenau-2022.yaml
Passage à l'état obsolète du projet 2019
> Fix dates projet Haguenau

- components/hero.js
> Correction des espacements/marge dans le hero 

- data/eureloir-chartres.yaml
- data/hautegaronne-sdehg.yaml
Fix sur les projets de Chartres et Haute-Garonne grâce à @Almodys 
Closes #97
> Fix projets existants

- package.json
- server/util/mongo.js
Cette PR ajoute l'import du module `process`dans la partie serveur.
Elle modifie la configuration de XO pour éviter de nouvelles erreurs
> Correction d’un problème d’import

- components/footer.js
- components/header.js
- components/modal.js
- components/suivi-form/authentification-modal.js
- components/text-input.js
- lib/authentification.js
- pages/formulaire-suivi.js
> Authentification par token

- data/energie-vienne-principale.yaml
- data/vienne-principal.yaml
Ajout du projet Energie Vienne
> Projet energie vienne

- data/landes-montdemarsan.yaml
- data/mont-de-marsan-principal.yaml
Ajout du projet Mont-de-Marsan Agglo - Tranche principale
⚠️ Pas de nature pour les livrables
> Projet mont-de-marsan

- components/blog/blog-tags.js
- components/button.js
- components/header.js
- components/modal.js
- layouts/main.js
Reverts openpcrs/pcrs.beta.gouv.fr#132
> Revert "Ajustement d'affichage du menu de navigation mobile"

- components/map-sidebar/project-header.js
- components/map/map.js
- layouts/map.js
- pages/suivi-pcrs.js
Cette PR corrige le problème de synchronisation entre le panneau latéral et la carte.
Fix #167 
Captures : 
Avant : 
Après :
> Correction de la synchronisation des données entre le panneau latéral et la carte

- components/map-sidebar/index.js
- components/suivi-form/acteurs/acteur-card.js
- components/suivi-form/acteurs/acteur-form.js
- components/text-input.js
Il manquait un champ permettant à l'utilisateur de rentrer un email dans le formulaire d'ajout d'acteur.
Close #172
> Ajout d'un champ "email"

- components/suivi-form/perimetres/perimetre-form.js
- lib/decoupage-administratif-api.js
Cette PR ajoute la possibilité d'effectuer une recherche de commune via son code INSEE dans la section `Périmètres` du formulaire de suivi.
https://user-images.githubusercontent.com/66621960/236181896-8303ecba-b1bf-42c5-9dd4-4106a286b764.mov
> Recherche de la commune par code INSEE

- components/suivi-form/livrables/livrable-form.js
- components/suivi-form/perimetres/index.js
Cette PR retire l'astérisque en trop pour le champ diffusion (formulaire de `livrable`) et ajoute un bandeau d'information concernant les référentiels INSEE.
> Correction wording formulaire

- components/digit-code-input.js
- components/suivi-form/perimetres/index.js
Création d'un composant réutilisable permettant de recevoir un code d'authentification.
`codeValue` : <string> Valeur de l'input - _required_ -
`handleCodeValue` : <function> Méthode de récupération de la valeur de l'input - _required_ -
`codeLength` : <number> Taille du code - _default => `6`_ -
`isRequired` : <bool> Indique si le champ est requis ou non - _default => `false`_ -
https://user-images.githubusercontent.com/66621960/236248998-0bf2b793-0431-46b1-91c5-ceade93bc7e1.mov
> Composant champ d'authentification

- components/footer.js
- components/map-sidebar/project-header.js
- components/map/map.js
- components/suivi-form/authentification-modal.js
- components/suivi-form/index.js
- components/text-input.js
- contexts/authentification-token.js
- pages/_app.js
Cette PR ajoute un contexte permettant de stocker et récupérer le token d'authentification. 
Le token renvoie : 
`isAdmin` : _<boolean>_ Désigne si l'utilisateur bénéficie ou non du statut d'administrateur.
`token` : _<string>_ Token d'authentification.
`storeToken` : _<func>_ Méthode de stockage du token dans le `localStorage`.
Close  #150
> Création d'un contexte d'authentification

- server/projets.js
- server/util/mongo.js
Cette PR ajoute une fonction qui sauvegarde l'état d'un projet lorsqu'il est créé ou modifié. 
Le projet est enregistré dans une collection `versions` ce qui permettra de restaurer les versions précédentes en cas de problème.
> Ajout d'une collection pour conserver les versions des projets

- components/map-sidebar/index.js
- components/map-sidebar/project-header.js
- components/map/map.js
- components/suivi-form/index.js
- lib/suivi-pcrs.js
- pages/formulaire-suivi.js
- pages/suivi-pcrs.js
Cette PR permet de récupérer et utiliser le code d'édition pour construire l'url menant à la page d'édition d'un projet en tant qu'administrateur
> Correction de la clé editeur admin

- components/suivi-form/acteurs/acteur-card.js
- components/suivi-form/acteurs/index.js
- components/suivi-form/livrables/index.js
- components/suivi-form/livrables/livrable-card.js
Un titre et/ou une adresse mail longue posait un problème de superposition et rendait les informations illisibles dans la carte `acteur`.
Le nouveau design d'affichage d'informations sur deux étages est aussi appliqué à la carte `livrable`.
> Amélioration du responsive des cartes acteur et livrable

- events.json
Ajout de l'atelier du 30/06 à l'agenda
> Atelier du 30/06 à l'agenda

- components/map-sidebar/project-header.js
- components/map-sidebar/reset-modal.js
- components/modal.js
- components/suivi-form/livrables/index.js
- components/suivi-form/share-modal.js
- components/tooltip.js
- lib/suivi-pcrs.js
**⚠️ À ne merger que lorsque la PR Ajout d’une route administrateur pour renouveler la clé d’édition d’un projet #205 est elle même validée et mergée**
* ### Point d'entrée sur la sidebar pour les administrateurs seulement
* ### Affichage du lien d'édition actuel avec possibilité de copier 
* ### Double confirmation 
* ### Rechargement de la page après un timer pour remettre les données de la carte à jour
> Interface réinitialisation du code éditeur par l'admin 

- server/admin/reports.js
- server/index.js
- server/projets.js
- server/util/mongo.js
Cette PR ajoute une route `/report` permettant d'afficher les projets créés / modifiés / supprimés dans les dernières 24h.
Cette route permettra d'afficher les derniers changements du suivi PCRS dans l'espace administration.
> Ajout de la route `/report` 

- server/admin/creators-emails.js
Correction d’une faute dans le message d’erreur de la fonction `addCreator`
> Correction d’une faute dans un message d’erreur

- components/autocomplete-input.js
Cette PR permet une navigation au clavier du champ d'autocomplétion, permettant accessibilité et amélioration de l'ergonomie.
> Navigation par clavier de l'autocomplete

- pages/calculatrice.js
- server/calculator.js
- server/routes/calculator.js
La calculatrice de coût ayant été mergée rapidement avant les Géodatadays, certaines parties du code n’étaient pas très claires et il manquait la fonctionnalité de calcul par taille de fichier.
- Renommage de variables et de fonctions pour des noms plus clairs
- Amélioration du "responsive" et du style
- Mise en valeur du résumé
- Ajout d’une fonction pour formater la taille de fichier (Go ou To)
- Ajout de la fonction de calcul par taille de fichier
> Amélioration de la calculatrice

- components/map/map.js
> Corrige le problème d’id désynchronisés entre mobile et desktop

- components/date-input.js
- components/suivi-form/acteurs/index.js
- components/suivi-form/index.js
- components/suivi-form/livrables/index.js
- components/suivi-form/livrables/livrable-card.js
- components/suivi-form/livrables/livrable-form.js
- components/suivi-form/livrables/utils/select-options.js
- lib/utils/select-options.js
- reducers/form-reducer.js
Le code des composants du formulaire de livrables souffre de quelques erreurs de conception et est assez complexe à maintenir.
Cette PR corrige les différents problèmes du composant et met en place l'utilisation d’un `reducer` afin de faciliter l'intégration des prochains développement et la maintenabilité du code du formulaire.
> Reprise du code du formulaire de livrables

- components/projet/list-render-items.js
- components/projet/livrables-section.js
- components/projet/scanned-data.js
- components/projet/scanner-map.js
- components/projet/stockage-data.js
- components/projet/stockage-preview.js
- lib/date-utils.js
- lib/pcrs-scanner-api.js
- lib/utils/file.js
- lib/utils/projet.js
- pages/projet/[id].js
Ajout d'une section permettant de visualiser les informations consolidées d'un livrable :
- Partie stockage 
- Partie scanner avec les informations consolidés et la carte de visualisation des fichiers
> Ajout de la partie scanner sur la page projet

- backend/lib/models/projets.js
Ne retourne les paramètres de connexion aux stockages que si ceux-ci sont définis comme publics.
> Sécurise les paramètres de connexion aux stockages

- backend/__tests__/projets.js
- package.json
Cette PR corrige les tests : 
- Ajout d’une variable d’environnement dans la configuration `ava`
- Modification d’un test (récupération du projet complet avant de filtrer)
> Correction des tests en erreur

- components/containers/dropdown-list.js
- components/projet/livrables-section.js
- components/projet/scan-result.js
- components/projet/scanned-data.js
- components/projet/stockage-data.js
- components/projet/stockage-preview.js
- lib/pcrs-scanner-api.js
- lib/suivi-pcrs.js
- lib/utils/projet.js
- lib/utils/request.js
- pages/suivi-pcrs.js
Quelques erreurs ou lourdeur dans le code se sont glissés dans les composants liés à l’affichage des stockages. Cette PR a pour objectif de les corriger et de simplifier le code.
- Correction d’une coquille sur le nom du composant `<CenteredSpinner>`
- Correction de la déclaration des propTypes de `StockageData`
- Ajout d'un fichier `request.js` dans les `/utils` permettant d'uniformiser une partie des appels `fetch` de l'application
- Ajout d'un composant `<ScanResult>` dédié à l’affichage du résultat du scanner
- Utilisation de `params` issue du livrable et non de l'API Scanner qui ne le renvoi plus
- L'affichage du wrapper dépend désormais du type de stockage et non de l'existance de `params`
- Ajout d'un composant `DropdownList` pour éviter le code dupliquer, mais aussi facilité …
> Correction et amélioration des composants liés au stockage

- components/footer.js
> Corrige l’accès à l’espace d’administration

- pages/index.js
> Corrige le problème de double icône sur les boutons de réseaux sociaux

- lib/entreprises-api.js
Cette pull request corrige l'URL de l'api-entreprise.
> Corrige l'URL du tracker api-entreprise 

- .well-known/security.txt
> Ajout d'un fichier security.txt

- components/suivi-form/livrables/livrable-card.js
Fix d'une erreur de propstypes
> Fix stockage_erreur not in propstypes

- backend/export/csv.js
- components/suivi-form/general-infos.js
Deux coquilles simples à corriger
> Fix champs des exports CSV

- backend/export/stockage.js
Ajout d'un champ licence dans les exports livrables et dalles
> Fix licence dans les exports livrables/dalles

- backend/__tests__/projets-validator.js
- backend/export/csv.js
- backend/export/stockage.js
- backend/lib/projets-validator.js
- components/suivi-form/livrables/livrable-card.js
- components/suivi-form/livrables/livrable-form.js
Cette pull request ajoute un champ "diffusion_layer" dans les projets.
- Ajout du champ dans le formulaire (création / édition)
- Ajout de la propriété dans la validation (création / édition)
- Légère modification du visuel du formulaire
- Légère modification du visuel de la carte qui affiche le livrable
- Ajout de la propriété dans les tests
Fix #457
> Ajout d’un champ "diffusion_layer"

- backend/__tests__/projets-validator.js
- backend/export/csv.js
- backend/export/stockage.js
- backend/lib/projets-validator.js
- components/suivi-form/livrables/livrable-card.js
- components/suivi-form/livrables/livrable-form.js
Reverts openpcrs/pcrs.beta.gouv.fr#459
> Revert "Ajout d’un champ "diffusion_layer""

- backend/__tests__/projets-validator.js
- backend/export/csv.js
- backend/export/stockage.js
- backend/lib/projets-validator.js
- components/suivi-form/livrables/livrable-card.js
- components/suivi-form/livrables/livrable-form.js
Cette pull request ajoute un champ "diffusion_layer" dans les projets.
- Ajout du champ dans le formulaire (création / édition)
- Ajout de la propriété dans la validation (création / édition)
- Légère modification du visuel du formulaire
- Légère modification du visuel de la carte qui affiche le livrable
- Ajout de la propriété dans les tests
Fix #457 
> Nouvelle PR après avoir remarqué des soucis de validation avec la précédente #459
> Ajout du champ diffusion_layer - redo

- backend/lib/models/projets.js
- backend/lib/projets-validator.js
- components/map/index.js
- components/map/legend.js
- components/map/styles/vector.json
- components/suivi-form/utils/general-select-options.js
- lib/utils/projet.js
Modifications visant à :
* Ajouter un régime anticipation
* Créer le filtre carto associé
Fix #453
> Ajout d'un régime anticipation et du filtre carto associé

- package.json
Cette pull request supprime le lancement du script de migration qui ajoute le champ "millesime".
> Enlève le lancement du script au démarrage 

- components/suivi-form/livrables/utils/select-options.js
- lib/utils/projet.js
Prise en charge d'un nouveau format au fil de l'eau à la demande d'un porteur de projet
> Support du format Geopackage vecteur

- components/suivi-form/index.js
> Fix suivi-form champ budget non formatté en nombre

- events.json
Ajout d'un événement et mise à jour de liens rétrospectifs dans le calendrier
> Ajout webinaire 2025-02-06

- components/suivi-form/index.js
> Fix du message discordance des millésime dans le formulaire d'édition

- utils/grist-sync/.env.sample
- utils/grist-sync/.gitignore
- utils/grist-sync/README.md
- utils/grist-sync/requirements.txt
- utils/grist-sync/src/sync.py
Il s'agit du code utilisé pour synchroniser la base grist des projets avec le suivi maintenu sur la plateforme
> Ajout de l'utilitaire permettant la synchro avec grist

- backend/lib/projets-validator.js
- components/suivi-form/etapes.js
Ces modifications suppriment le contrôle de la chronologie des étapes d'un projet.
> Supprime le contrôle de la chronologie des étapes
